import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/sections/Navbar";
import { NavigationProvider } from "@/components/layout/NavigationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload Interstate fonts */}
        <link
          rel="preload"
          href="/fonts/interstate-regular-comp.woff"
          as="font"
          type="font/woff"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/interstate-bold-cond.woff"
          as="font"
          type="font/woff"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/interstate-light-cond.woff"
          as="font"
          type="font/woff"
          crossOrigin="anonymous"
        />
      </head>
      <body className="antialiased bg-[#f9f9f6] text-[#2e2e38]">
        <NavigationProvider>
          <Navbar />
          <main className="relative">{children}</main>
        </NavigationProvider>
      </body>
    </html>
  );
}